from PyQt5 import QtCore, QtGui, QtWidgets


class ProblemWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("ProblemWindow")
        MainWindow.resize(1920, 1080)

        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 531, 1081))
        self.frame.setStyleSheet("background-color: rgb(86, 86, 86)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 50, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 282, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 125, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 425, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 346, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 982, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(1030, 311, 391, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(1045, 678, 361, 111))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton.setObjectName("pushButton")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(810, 429, 825, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(940, 550, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_9.setObjectName("label_9")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(1111, 550, 411, 57))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MathSolver"))
        self.label_2.setText(_translate("MainWindow", "Легких: 0"))
        self.label_3.setText(_translate("MainWindow", "Юзернейм:"))
        self.label_4.setText(_translate("MainWindow", "Выполнено примеров:"))
        self.label_5.setText(_translate("MainWindow", "Сложных: 0"))
        self.label_6.setText(_translate("MainWindow", "Средних: 0"))
        self.pushButton_4.setText(_translate("MainWindow", "Выход"))
        self.label_7.setText(_translate("MainWindow", "Решите пример:"))
        self.pushButton.setText(_translate("MainWindow", "Ввести ответ"))
        self.label_8.setText(_translate("MainWindow", "пример "))
        self.label_9.setText(_translate("MainWindow", "Ответ:"))


class LoginWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("LoginWindow")
        MainWindow.resize(1920, 1080)
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.widgets = []
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(504, 70, 911, 171))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(100)
        self.label.setFont(font)
        self.label.setStyleSheet("color:rgb(255, 255, 255)")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(370, 260, 1181, 151))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(50)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(584, 700, 331, 71))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(32)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(584, 500, 121, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(40)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(584, 590, 231, 61))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(40)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color:rgb(255, 255, 255)")
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(860, 870, 201, 91))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(32)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color:rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(920, 690, 441, 91))
        font = QtGui.QFont()
        font.setFamily("Impact")
        font.setPointSize(32)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color:rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(820, 590, 541, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color:rgb(255, 255, 255)")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(730, 500, 631, 61))
        font = QtGui.QFont()
        font.setFamily("Sitka Display")
        font.setPointSize(32)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color:rgb(255, 255, 255)")
        self.lineEdit_2.setObjectName("lineEdit_2")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Здравствуй!"))
        self.label_2.setText(_translate("MainWindow", "Спасибо, что выбрал MathSolver!"))
        self.label_3.setText(_translate("MainWindow", "Нет аккаунта?"))
        self.label_4.setText(_translate("MainWindow", "Ник:"))
        self.label_5.setText(_translate("MainWindow", "Пароль:"))
        self.pushButton.setText(_translate("MainWindow", "Войти"))
        self.pushButton_2.setText(_translate("MainWindow", "Зарегистрируйся!"))


class MainMenu(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainMenu")
        MainWindow.resize(1920, 1080)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1080))
        MainWindow.setMaximumSize(QtCore.QSize(1920, 1080))
        MainWindow.setStyleSheet("background-color: rgb(54, 54, 54);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 531, 1081))
        self.frame.setStyleSheet("background-color: rgb(86, 86, 86)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(50, 50, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(50, 282, 461, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(50, 125, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(50, 200, 461, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(50, 425, 411, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(50, 346, 331, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_6.setObjectName("label_6")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame)
        self.pushButton_4.setGeometry(QtCore.QRect(50, 982, 141, 51))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(850, 430, 751, 61))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_7.setObjectName("label_7")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(740, 590, 250, 110))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(1100, 590, 250, 110))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(1460, 590, 250, 110))
        font = QtGui.QFont()
        font.setPointSize(32)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setStyleSheet("color: rgb(255, 255, 255);background-color: rgb(167,167,167)")
        self.pushButton_3.setObjectName("pushButton_3")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "MathSolver"))
        self.label_2.setText(_translate("MainWindow", "Легких: 0"))
        self.label_3.setText(_translate("MainWindow", "Юзернейм:"))
        self.label_4.setText(_translate("MainWindow", "Выполнено примеров:"))
        self.label_5.setText(_translate("MainWindow", "Сложных: 0"))
        self.label_6.setText(_translate("MainWindow", "Средних: 0"))
        self.pushButton_4.setText(_translate("MainWindow", "Выход"))
        self.label_7.setText(_translate("MainWindow", "Выберите сложность примера:"))
        self.pushButton.setText(_translate("MainWindow", "Легкий"))
        self.pushButton_2.setText(_translate("MainWindow", "Средний"))
        self.pushButton_3.setText(_translate("MainWindow", "Сложный"))


class RegWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("RegWindow")
        Dialog.resize(480, 620)
        Dialog.setMinimumSize(QtCore.QSize(480, 620))
        Dialog.setMaximumSize(QtCore.QSize(480, 620))
        Dialog.setStyleSheet("background-color: rgb(54, 54, 54);")

        self.widgets = []

        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(160, 70, 161, 51))
        self.label.setStyleSheet("color:rgb(255, 255, 255);font-size:16pt\n""")
        self.label.setObjectName("label")
        self.widgets.append(self.label)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 200, 51, 21))
        self.label_2.setStyleSheet("font-size:15pt;color:rgb(255, 255, 255)\n""")
        self.label_2.setObjectName("label_2")
        self.widgets.append(self.label_2)

        self.login = QtWidgets.QLineEdit(Dialog)
        self.login.setGeometry(QtCore.QRect(90, 190, 371, 41))
        self.login.setObjectName("login")
        self.widgets.append(self.login)

        self.password = QtWidgets.QLineEdit(Dialog)
        self.password.setGeometry(QtCore.QRect(130, 240, 331, 41))
        self.password.setObjectName("password")
        self.widgets.append(self.password)

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(30, 246, 91, 31))
        self.label_3.setStyleSheet("font-size:15pt;color:rgb(255, 255, 255)\n""")
        self.label_3.setObjectName("label_3")
        self.widgets.append(self.label_3)

        self.loginbutton = QtWidgets.QPushButton(Dialog)
        self.loginbutton.setGeometry(QtCore.QRect(134, 400, 211, 41))
        self.loginbutton.setStyleSheet("background-color: rgb(167,167,167);font-size:12pt;color:rgb(255, 255, 255)")
        self.loginbutton.setObjectName("loginbutton")
        self.widgets.append(self.loginbutton)

        self.password_ret = QtWidgets.QLineEdit(Dialog)
        self.password_ret.setGeometry(QtCore.QRect(250, 290, 211, 41))
        self.password_ret.setObjectName("password_ret")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.widgets.append(self.password_ret)

        self.label_4.setGeometry(QtCore.QRect(30, 296, 215, 31))
        self.label_4.setStyleSheet("font-size:15pt;color:rgb(255, 255, 255)\n""")
        self.label_4.setObjectName("label_4")
        self.widgets.append(self.label_4)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Регистрация"))
        self.label_2.setText(_translate("Dialog", "Ник"))
        self.label_3.setText(_translate("Dialog", "Пароль"))
        self.loginbutton.setText(_translate("Dialog", "Зарегистрироваться"))
        self.label_4.setText(_translate("Dialog", "Повторите пароль"))